#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/

ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/hcl-aida-orchestrator:${VERSION} AS base


COPY ./redis/redis.key .
COPY ./redis/ca.pem .

FROM base AS builder

ENTRYPOINT ["python", "-m", "Orchestrator.py"]

FROM base AS debug

RUN pip install debugpy

CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5678 Orchestrator.py
