#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/

ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/hcl-aida-exporter:${VERSION} AS base

WORKDIR /usr/src/app

FROM base AS builder

CMD python3 ./exporter.py
#CMD gunicorn -b 0.0.0.0:5000 -k gthread 'server:app'

FROM base AS debug

RUN pip install debugpy

CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5678 exporter.py