#/*******************************************************************************
#* Licensed Materials - Property of HCL 
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved. 
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/

ARG REGISTRY
ARG VERSION
FROM ${REGISTRY}/hcl-aida-ad:${VERSION} AS base

#Exposing at port 5000
EXPOSE 5000

FROM base AS builder

# command to run on container start
CMD gunicorn -b 0.0.0.0:5000 -k gthread 'server:app'

FROM base AS debug

RUN pip install debugpy

CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m gunicorn -b 0.0.0.0:5000 -k gthread --reload -t 0 'server:app'
