#/*******************************************************************************
#* Licensed Materials - Property of HCL
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved.
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
version: "3.0"

services:
    config:
        image: hclcr.io/wa/workload-automation/hcl-aida-config:10.1.0.3
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        container_name: aida-config
        env_file: common.env
        networks:
            - aida-net
        tty: true
        profiles:
            - config
        volumes:
            - $PWD:/docker-deployment

    nginx:
        build:
            context: .
            dockerfile: "Dockerfile-nginx"
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-nginx
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        ports:
            - "9432:9432"
        links:
            - ui
            - exporter
            - ad
            - email
            - orchestrator
            - predictor
            - redis
        depends_on:
            - ui
        restart: unless-stopped

    ui:
        build:
            context: .
            dockerfile: "Dockerfile-ui"
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-ui
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        expose:
            - "9000"
        links:
            - es
            - redis
        depends_on:
            - es
            - redis
        restart: unless-stopped

    exporter:
        build:
            context: .
            dockerfile: "Dockerfile-exporter"
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
            target: builder
        container_name: aida-exporter
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        links:
            - es
        depends_on:
            - es
        restart: unless-stopped

    ad:
        build:
            context: .
            dockerfile: "Dockerfile-ad"
            target: builder
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-ad
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        expose:
            - "5000"
        links:
            - es
            - redis
        depends_on:
            - es
            - redis
        restart: unless-stopped

    email:
        build:
            context: .
            target: builder
            dockerfile: "Dockerfile-email"
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-email
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        expose:
            - "5000"
        links:
            - redis
        depends_on:
            - redis
        restart: unless-stopped

    orchestrator:
        build:
            dockerfile: Dockerfile-orchestrator
            context: .
            target: builder
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-orchestrator
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        links:
            - es
            - redis
            - predictor
            - ad
        depends_on:
            - es
            - redis
            - predictor
            - ad
        restart: unless-stopped

    predictor:
        build:
            context: .
            dockerfile: "Dockerfile-predictor"
            target: builder
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-predictor
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        tty: true
        env_file: common.env
        networks:
            - aida-net
        expose:
            - "5000"
        links:
            - es
            - redis
        depends_on:
            - es
            - redis
        restart: unless-stopped
    redis:
        build:
            context: .
            dockerfile: "Dockerfile-redis"
            args:
                - REGISTRY:${REGISTRY}
                - VERSION:${VERSION}
        container_name: aida-redis
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        env_file: common.env
        networks:
            - aida-net
        expose:
            - "6379"
        restart: unless-stopped

    es:
        build:
            context: .
            dockerfile: "Dockerfile-es"
        container_name: aida-es
        logging:
            options:
                max-size: "100m"
                max-file: "3"
        #env_file: common.env
        environment:
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        networks:
            - aida-net
        expose:
            - "9200"
            - "9300"
            - "9600"
        volumes:
            - aida-es-data:/usr/share/opensearch/data
        restart: unless-stopped

# Local volumes cannot be used for deployment in clusters
volumes:
    aida-es-data:
networks:
    aida-net:
